orangemo:
  profile: E:/orangemo/uploadPath
  ignores: /file/common/upload,/login
server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://43.140.246.157:3306/orange_admin?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: Houzhi1227@
    driver-class-name: com.mysql.cj.jdbc.Driver